In [10]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

datasets = load_dataset('lukebarousse/data_jobs')
df = datasets['train'].to_pandas()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.head()

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                               None
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]